jupyterhub:
  proxy:
    secretToken: SECRET

  auth:
    type: github
    github:
      clientId: "7cff830335e085d71c98"
      clientSecret: SECRET
      callbackUrl: "http://35.232.36.204/hub/oauth_callback"
    admin:
      access: true
      users:
        - TomAugspurger
        - jcrist
        - martindurant
